task1 arm64 asm completed
KKiiim/NewStaffLearningTask pull request #1
Opened 2024-02-28 07:48 UTC by yyhuang95

arm64 asm task completed

2024-02-28 08:57 UTC, KKiiim requested changes

2024-02-28 08:57 UTC, KKiiim commented on .github/workflows/c-cpp.yml
> +    branches: [ "main" ]
should ON pull_request that will trigger github action.

2024-02-28 08:57 UTC, KKiiim commented on googleTest.cc
> +
Do not need comment other TESTs, gtest supports multi tests that will show the all results in github action .

2024-02-28 08:57 UTC, KKiiim commented on googleTest.cc
> +
the same.

2024-02-28 08:57 UTC, KKiiim commented on googleTest.cc
> +}
All qsort function details should implement with arm64 assembly. In test, the caller only call single function and get result. That means, the function QuickSort logic should also assembly written.

2024-02-29 01:18 UTC, yyhuang95 commented
branch has moved from my own repo to arm64 branch in this repo, I will fix these problems and open a new pull-request

2024-02-29 03:29 UTC, closed without merging