task2 wasm completed
KKiiim/NewStaffLearningTask pull request #5
Opened 2024-03-04 06:39 UTC by yyhuang95

2024-03-04 07:26 UTC, KKiiim requested changes

2024-03-04 07:26 UTC, KKiiim commented on wasm.test.js
> +describe('test wasm', function() {
test did not work in CI action

2024-03-04 07:26 UTC, KKiiim commented on .github/workflows/c-cpp.yml
> -          make && sudo make install
remain the old test and append the new, organize src and test files in your repo

2024-03-05 02:46 UTC, XMadrid commented on .github/workflows/wasm.yml
> +          sudo apt install nodejs
it's better to use actions/setup-node

2024-03-05 02:46 UTC, XMadrid commented on .github/workflows/wasm.yml
> +          npm install -g mocha
use `npm ci` to install dependencies.

2024-03-05 02:46 UTC, XMadrid commented on .github/workflows/wasm.yml
> +          npx run mocha wasm.test.js
`cd wasm && npm run test`

2024-03-07 02:11 UTC, KKiiim requested changes

2024-03-07 02:11 UTC, KKiiim commented on wasm/wasm.test.js
> +            assert.equal(true, assertQS(mem, 0, raw_values.length))
use mocha test

2024-03-07 05:48 UTC, KKiiim approved these changes

2024-03-07 05:51 UTC, merged